[package]
name = "mistralrs-paged-attn"
readme = "README.md"
authors = ["Eric Buehler"]
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
candle-core.workspace = true
half.workspace = true
float8.workspace = true
metal = { workspace = true, optional = true }
thiserror = "1"
once_cell = "1.20.2"

[build-dependencies]
bindgen_cuda = {git = "https://github.com/guoqingbao/bindgen_cuda.git", version = "0.1.6", optional = true}
anyhow.workspace = true

[features]
cuda = ["dep:bindgen_cuda"]
metal = ["dep:metal"]